config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'

  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/shared/_delete_micropost.html.erb
	<%#= render 'delete_micropost', mp: @feed_items) %>
    <%= link_to "delete", mp, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: mp.content %>

app/views/shared/_error_messages.html.erb

  <!-- the "alert alert-error" class below enables
    bootstrap to surround the "form contains.." with red
    and prints the error messages in red
  -->

<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<%# called from views/shared/signed_in.html.erb %>

<% if @feed_items.any? %>
  <ol class="microposts">
  <%#= render partial: 'shared/feed_item', collection: @feed_items, as: :item %>

  <%#= render'shared/view_microposts', item: @feed_items.first, object: true%>

  <%# cannot get the object cases to work %>

  <%#= render partial: 'shared/view_microposts', collection: @feed_items, as: :item, object: true %>

  <%= render partial: 'shared/view_microposts', collection: @feed_items, as: :item, locals:  {feedpath: true} %>
  
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= item.id %>">
  <%= link_to gravatar_for(item.user), item.user %>
  <span class="user">
    <%= link_to item.user.name, item.user %>
  </span>
  <span class="content"><%= wrap(item.content) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(item.created_at) %> ago.
  </span>
  <% if current_user?(item.user) %>
    <%= render 'shared/delete_micropost', mp: item %>
    <%#= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>     
  
  <%#= render partial: 'shared/view_microposts', mp: feed_item %>
</li>


app/views/shared/_micropost_form.html.erb
<%# _micropost_form.html.erb %>
<%# called from views/shared/signed_in.html.erb %>

<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_signed_in.html.erb
<%#  views/shared/_signed_in %>
<%#  called from home view  (views/static_pages/home.html.erb) %>

  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>

      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>  

app/views/shared/_stats.html.erb
<%#app/views/shared/_stats.html.erb %>

<% @user ||= current_user %>
<%#
As discussed in Box 8.2, this does nothing when @user is not nil (as on a profile page), but when it is (as on the Home page) it sets @user to the current user.
%>

<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>


app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shared/_view_microposts.html.erb
  <% if feedpath %>
   <%# if view_microposts %>
    <li id="<%= item.id %>">
    <%= link_to gravatar_for(item.user), item.user %>
    <span class="user">
    <%= link_to item.user.name, item.user %>
    </span>
  <% else  %> 
    <li>
  <% end  %>
  <span class="content"><%= wrap(item.content) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(item.created_at) %> ago.
  </span>
  <% if current_user?(item.user) %>
    <%= render 'shared/delete_micropost', mp:item %>
    <%#= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %> 
  </li> 

app/views/shared/_view_refact_microposts.html.erb

  <li>
    <%= render 'shared/view_microposts', item: r_item %>

      <%#= to pass the local variable "item" above, must leave out "partial:" after the "render" %>
  </li>
  

app/views/shared/_welcome_page.html.erb
<%#  views/shared/_welcome_page %>
<%#  called from home view  (views/static_pages/home.html.erb) %>

  <div class="center hero-unit">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>